#!/usr/bin/env node
/**
 * Downloads the bundled web fonts from Google Fonts into public/fonts/ and writes
 * src/render/font-faces.ts (the manifest the renderer turns into @font-face rules).
 *
 * Only the `latin` and `latin-ext` subsets are kept, to keep the offline cache small.
 * Files already in public/fonts/ are not downloaded again. Edit FONTS_CSS_URL to add
 * a family or weight, then run: npm run fonts
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'public', 'fonts');
const MANIFEST = path.join(ROOT, 'src', 'render', 'font-faces.ts');
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FONTS_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900' +
  '&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900' +
  '&family=Montserrat:ital,wght@0,100..900;1,100..900' +
  '&family=Open+Sans:ital,wght@0,300..800;1,300..800' +
  '&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap';

// Google serves woff2 with per-subset @font-face blocks only to modern browsers.
const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15';

const css = await (await fetch(FONTS_CSS_URL, { headers: { 'User-Agent': USER_AGENT } })).text();
await fs.mkdir(FONT_DIR, { recursive: true });

const faces = [];
for (const [, subset, body] of css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{(.*?)\}/gs)) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const family = body.match(/font-family: '([^']+)'/)[1];
  const style = body.match(/font-style: (\w+)/)[1];
  const weight = body.match(/font-weight: ([\d ]+);/)[1].trim();
  const url = body.match(/url\((\S+)\)/)[1];
  const range = body.match(/unicode-range: (.*?);/)[1];
  const file = `${family.toLowerCase().replace(/ /g, '-')}-${style}-${weight.replace(' ', '-')}-${subset}.woff2`;
  const dest = path.join(FONT_DIR, file);
  try {
    await fs.access(dest);
  } catch {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    await fs.writeFile(dest, Buffer.from(await res.arrayBuffer()));
  }
  faces.push({ family, style, weight, file, range });
}

faces.sort((a, b) => a.family.localeCompare(b.family) || a.style.localeCompare(b.style) || a.file.localeCompare(b.file));

const rows = faces
  .map((f) => `  { family: '${f.family}', style: '${f.style}', weight: '${f.weight}', file: '${f.file}', range: '${f.range}' },`)
  .join('\n');
await fs.writeFile(
  MANIFEST,
  `/**
 * GENERATED by scripts/make-fonts.mjs (npm run fonts): do not edit by hand.
 * One entry per file in public/fonts/. All families are licensed under the SIL Open Font License.
 */
export interface FontFaceEntry {
  family: string;
  style: 'normal' | 'italic';
  /** a single weight ("400") or a variable range ("100 900") */
  weight: string;
  /** file name inside public/fonts/ */
  file: string;
  unicodeRange: string;
}

export const FONT_FACES: FontFaceEntry[] = [
${rows.replace(/range:/g, 'unicodeRange:')}
] as FontFaceEntry[];
`,
);
console.log(`${faces.length} font files in public/fonts, manifest written to src/render/font-faces.ts`);
